#!/usr/bin/env python3
"""
HOL-01 exact finite certificate.

Scope
-----
This program certifies finite statements about the congruence graphs generated by
Barning-Berggren matrices acting on the Pythagorean cone x^2 + y^2 - z^2 = 0.
The main publication target is p=7 (mod 49 over mod 7).  The same finite checks
are also run at p in {3,5,7,11,13} as regression evidence; they are NOT a proof
for all odd primes.

No floating-point arithmetic and no third-party package is used.
Exit status is non-zero if any asserted statement fails.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from collections import Counter, deque
from pathlib import Path
from typing import Iterable

# Barning-Berggren/Romik matrices, acting on column vectors.
M1 = ((-1, 2, 2), (-2, 1, 2), (-2, 2, 3))
M2 = ((1, 2, 2), (2, 1, 2), (2, 2, 3))
M3 = ((1, -2, 2), (2, -1, 2), (2, -2, 3))
J = ((1, 0, 0), (0, 1, 0), (0, 0, -1))
I3 = ((1, 0, 0), (0, 1, 0), (0, 0, 1))
R = (3, 4, 5)
I2 = (1, 0, 0, 1)
TEST_PRIMES = (3, 5, 7, 11, 13)


def mm0(A, B):
    return tuple(tuple(sum(A[i][k] * B[k][j] for k in range(3)) for j in range(3)) for i in range(3))


def mm(A, B, m):
    return tuple(tuple(sum(A[i][k] * B[k][j] for k in range(3)) % m for j in range(3)) for i in range(3))


def mv(A, v, m):
    return tuple(sum(A[i][k] * v[k] for k in range(3)) % m for i in range(3))


def tr(A):
    return tuple(tuple(A[j][i] for j in range(3)) for i in range(3))


def det3(A):
    return (
        A[0][0] * (A[1][1] * A[2][2] - A[1][2] * A[2][1])
        - A[0][1] * (A[1][0] * A[2][2] - A[1][2] * A[2][0])
        + A[0][2] * (A[1][0] * A[2][1] - A[1][1] * A[2][0])
    )


def red(A, m):
    return tuple(tuple(x % m for x in row) for row in A)


def inv_orth0(A):
    # A^{-1} = J A^T J for A^T J A = J.
    return mm0(mm0(J, tr(A)), J)


def inv_orth(A, m):
    return mm(mm(J, tr(A), m), J, m)


GENS_POS = (M1, M2, M3)
GENS = GENS_POS + tuple(inv_orth0(M) for M in GENS_POS)


def orbit(m: int):
    r = tuple(x % m for x in R)
    gs = tuple(red(g, m) for g in GENS)
    seen = {r}
    dq = deque([r])
    while dq:
        v = dq.popleft()
        for g in gs:
            w = mv(g, v, m)
            if w not in seen:
                seen.add(w)
                dq.append(w)
    return seen


def orbit_tree(p: int):
    """BFS tree in the mod-p orbit, storing a lift of each path mod p^2."""
    m = p * p
    r = tuple(x % p for x in R)
    P = {r: red(I3, m)}
    dq = deque([r])
    while dq:
        v = dq.popleft()
        for s0 in GENS:
            s = red(s0, m)
            w = mv(s, v, p)
            if w not in P:
                P[w] = mm(s, P[v], m)
                dq.append(w)
    return tuple(P), P


def tangent_basis(p: int):
    tangent = tuple(
        (a, b, c)
        for a in range(p)
        for b in range(p)
        for c in range(p)
        if (R[0] * a + R[1] * b - R[2] * c) % p == 0
    )
    assert len(tangent) == p * p
    z = (0, 0, 0)
    b1 = next(u for u in tangent if u != z)
    line = {tuple((k * x) % p for x in b1) for k in range(p)}
    b2 = next(u for u in tangent if u not in line)
    coord = {}
    for x in range(p):
        for y in range(p):
            u = tuple((x * b1[i] + y * b2[i]) % p for i in range(3))
            coord[u] = (x, y)
    assert len(coord) == p * p
    return tangent, (b1, b2), coord


# 2x2 and affine transformations on F_p^2.  Matrices are (a,b,c,d).
def m2mul(A, B, p):
    return (
        (A[0] * B[0] + A[1] * B[2]) % p,
        (A[0] * B[1] + A[1] * B[3]) % p,
        (A[2] * B[0] + A[3] * B[2]) % p,
        (A[2] * B[1] + A[3] * B[3]) % p,
    )


def m2v(A, b, p):
    return ((A[0] * b[0] + A[1] * b[1]) % p, (A[2] * b[0] + A[3] * b[1]) % p)


def m2inv(A, p):
    d = (A[0] * A[3] - A[1] * A[2]) % p
    di = pow(d, -1, p)
    return ((A[3] * di) % p, (-A[1] * di) % p, (-A[2] * di) % p, (A[0] * di) % p)


def m2pow(A, n, p):
    out = I2
    base = A
    while n:
        if n & 1:
            out = m2mul(base, out, p)
        base = m2mul(base, base, p)
        n >>= 1
    return out


def acomp(f, g, p):
    """Composition f o g for u -> A u + b."""
    A, b = f
    C, d = g
    AC = m2mul(A, C, p)
    Ad = m2v(A, d, p)
    return AC, ((Ad[0] + b[0]) % p, (Ad[1] + b[1]) % p)


def ainv(f, p):
    A, b = f
    Ai = m2inv(A, p)
    c = m2v(Ai, b, p)
    return Ai, ((-c[0]) % p, (-c[1]) % p)


def apow(g, n, p):
    out = (I2, (0, 0))
    base = g
    while n:
        if n & 1:
            out = acomp(base, out, p)
        base = acomp(base, base, p)
        n >>= 1
    return out


def aclosure(gens: Iterable, p: int):
    gens = list(dict.fromkeys(list(gens)))
    gens = list(dict.fromkeys(gens + [ainv(g, p) for g in gens]))
    e = (I2, (0, 0))
    seen = {e}
    dq = deque([e])
    while dq:
        x = dq.popleft()
        for g in gens:
            y = acomp(g, x, p)
            if y not in seen:
                seen.add(y)
                dq.append(y)
    return seen


def lclosure(gens: Iterable, p: int):
    gens = list(dict.fromkeys(list(gens)))
    gens = list(dict.fromkeys(gens + [m2inv(g, p) for g in gens]))
    seen = {I2}
    dq = deque([I2])
    while dq:
        x = dq.popleft()
        for g in gens:
            y = m2mul(g, x, p)
            if y not in seen:
                seen.add(y)
                dq.append(y)
    return seen


def elem_order_linear(A, p, cap=100000):
    x = I2
    for n in range(1, cap + 1):
        x = m2mul(A, x, p)
        if x == I2:
            return n
    raise AssertionError("linear element order exceeded cap")


def elem_order_affine(g, p, cap=100000):
    e = (I2, (0, 0))
    x = e
    for n in range(1, cap + 1):
        x = acomp(g, x, p)
        if x == e:
            return n
    raise AssertionError("affine element order exceeded cap")


def commute_affine(f, g, p):
    return acomp(f, g, p) == acomp(g, f, p)


def affine_from_loop(g, p, basis, coord):
    m = p * p
    r_m = tuple(x % m for x in R)
    g = red(g, m)
    assert mv(g, tuple(x % p for x in R), p) == tuple(x % p for x in R)
    gr = mv(g, r_m, m)
    t3 = tuple(((gr[i] - r_m[i]) % m) // p for i in range(3))
    b = coord[t3]
    gp = red(g, p)
    cols = [coord[mv(gp, bj, p)] for bj in basis]
    A = (cols[0][0], cols[1][0], cols[0][1], cols[1][1])
    return A, b


def schreier_affine_generators(p: int):
    m = p * p
    Vp, P = orbit_tree(p)
    _tangent, basis, coord = tangent_basis(p)
    out = []
    for v in Vp:
        for s0 in GENS:
            s = red(s0, m)
            w = mv(s, v, p)
            # P[w]^{-1} s P[v] is a loop at r modulo p.
            g = mm(mm(inv_orth(P[w], m), s, m), P[v], m)
            out.append(affine_from_loop(g, p, basis, coord))
    return tuple(dict.fromkeys(out)), basis, coord


def cycle_signature(g, p):
    def apply(x):
        A, b = g
        y = m2v(A, x, p)
        return ((y[0] + b[0]) % p, (y[1] + b[1]) % p)

    pts = [(a, b) for a in range(p) for b in range(p)]
    seen = set()
    lengths = []
    for x in pts:
        if x in seen:
            continue
        y = x
        n = 0
        while y not in seen:
            seen.add(y)
            y = apply(y)
            n += 1
        lengths.append(n)
    return sorted(lengths)


def check_dihedral(Lin, p):
    orders = {A: elem_order_linear(A, p) for A in Lin}
    rotations = {A for A, o in orders.items() if o in (1, p)}
    assert len(Lin) == 2 * p
    assert len(rotations) == p
    assert sum(1 for o in orders.values() if o == 2) == p
    rho = next(A for A, o in orders.items() if o == p)
    sigma = next(A for A, o in orders.items() if o == 2)
    assert m2mul(m2mul(sigma, rho, p), m2inv(sigma, p), p) == m2inv(rho, p)
    assert len(lclosure([rho, sigma], p)) == 2 * p
    return rotations, rho, sigma


def finite_prime_certificate(p: int):
    Vp = orbit(p)
    Vp2 = orbit(p * p)
    root_p = tuple(x % p for x in R)
    root_p2 = tuple(x % (p * p) for x in R)
    tangent, basis, coord = tangent_basis(p)

    # Exact covering fibres under reduction V_{p^2} -> V_p.
    counts = Counter(tuple(x % p for x in v) for v in Vp2)
    assert set(counts) == Vp
    assert set(counts.values()) == {p * p}
    root_fibre = {v for v in Vp2 if tuple(x % p for x in v) == root_p}
    tangent_fibre = {
        tuple((root_p2[i] + p * u[i]) % (p * p) for i in range(3))
        for u in tangent
    }
    assert root_fibre == tangent_fibre

    aff_gens, _basis, _coord = schreier_affine_generators(p)
    Mon = aclosure(aff_gens, p)
    Lin = lclosure([A for A, _b in aff_gens], p)
    rotations, _rho, _sigma = check_dihedral(Lin, p)
    translations = {g for g in Mon if g[0] == I2}
    U = {g for g in Mon if g[0] in rotations}

    complement = {g for g in Mon if g[1] == (0, 0)}
    assert len(Mon) == 2 * p ** 3
    assert len(translations) == p * p
    assert len(complement) == 2 * p and {g[0] for g in complement} == Lin
    assert {b for _A, b in translations} == {(x, y) for x in range(p) for y in range(p)}
    assert len(U) == p ** 3

    u_orders = {elem_order_affine(g, p) for g in U}
    assert u_orders <= {1, p}
    center = {x for x in U if all(commute_affine(x, y, p) for y in U)}
    assert len(center) == p
    assert any(not commute_affine(x, y, p) for x in U for y in aff_gens if y in U)

    return {
        "p": p,
        "V_p": len(Vp),
        "V_p2": len(Vp2),
        "fiber_degree": p * p,
        "schreier_affine_generators": len(aff_gens),
        "monodromy_order": len(Mon),
        "linear_image_order": len(Lin),
        "translation_kernel_order": len(translations),
        "zero_translation_complement_order": len(complement),
        "rotation_preimage_order": len(U),
        "rotation_preimage_center_order": len(center),
        "rotation_preimage_element_orders": sorted(u_orders),
    }, (basis, coord, Mon, U)


def p7_explicit_certificate(context):
    basis, coord, Mon, U = context
    A, B, C = M3, M2, M1
    # With column-vector left action, the positive word BABC has matrix C B A B.
    W1 = mm0(mm0(mm0(C, B), A), B)
    # Positive word BABAA has matrix A A B A B.
    W2 = mm0(mm0(mm0(mm0(A, A), B), A), B)

    assert W1 == ((55, 120, 132), (24, 55, 60), (60, 132, 145))
    assert W2 == ((49, 94, 106), (146, 287, 322), (154, 302, 339))
    assert mmv_exact(W1, R) == (1305, 592, 1433)
    assert mmv_exact(W2, R) == (1053, 3196, 3365)
    assert mv(W1, R, 7) == tuple(x % 7 for x in R)
    assert mv(W2, R, 7) == tuple(x % 7 for x in R)
    assert mv(W1, R, 49) == (31, 4, 12)
    assert mv(W2, R, 49) == (24, 11, 33)
    assert mv(W2, mv(W1, R, 49), 49) == (31, 32, 5)
    assert mv(W1, mv(W2, R, 49), 49) == (38, 25, 33)

    x = affine_from_loop(W1, 7, basis, coord)
    y = affine_from_loop(W2, 7, basis, coord)
    assert elem_order_affine(x, 7) == 7
    assert elem_order_affine(y, 7) == 7
    assert cycle_signature(x, 7) == [7] * 7
    assert cycle_signature(y, 7) == [7] * 7
    assert not commute_affine(x, y, 7)

    H = aclosure([x, y], 7)
    assert len(H) == 7 ** 3
    assert H == U
    z = acomp(acomp(acomp(x, y, 7), ainv(x, 7), 7), ainv(y, 7), 7)
    assert z != (I2, (0, 0))
    assert elem_order_affine(z, 7) == 7
    assert commute_affine(z, x, 7) and commute_affine(z, y, 7)
    assert apow(x, 7, 7) == (I2, (0, 0))
    assert apow(y, 7, 7) == (I2, (0, 0))
    assert apow(z, 7, 7) == (I2, (0, 0))
    center = {h for h in H if all(commute_affine(h, k, 7) for k in H)}
    assert len(center) == 7

    return {
        "word_gamma1": "BABC",
        "word_gamma2": "BABAA",
        "gamma1_matrix": W1,
        "gamma2_matrix": W2,
        "gamma1_r_integer": mmv_exact(W1, R),
        "gamma2_r_integer": mmv_exact(W2, R),
        "gamma1_r_mod49": mv(W1, R, 49),
        "gamma2_r_mod49": mv(W2, R, 49),
        "gamma1_cycle_signature_on_fiber": cycle_signature(x, 7),
        "gamma2_cycle_signature_on_fiber": cycle_signature(y, 7),
        "generated_index2_subgroup_order": len(H),
        "generated_subgroup_center_order": len(center),
        "commutator_order": elem_order_affine(z, 7),
        "noncommuting": True,
    }


def mmv_exact(A, v):
    return tuple(sum(A[i][k] * v[k] for k in range(3)) for i in range(3))


def ambient_sanity():
    assert [det3(M) for M in GENS_POS] == [1, -1, 1]
    assert all(mm0(mm0(tr(M), J), M) == J for M in GENS_POS)
    assert all(mm0(M, inv_orth0(M)) == I3 for M in GENS_POS)


def canonical_json(data):
    return json.dumps(data, indent=2, sort_keys=True) + "\n"


def main():
    parser = argparse.ArgumentParser(description="Exact HOL-01 finite congruence monodromy certificate")
    parser.add_argument("--write-json", type=Path, help="write deterministic results JSON")
    parser.add_argument("--check", type=Path, help="compare deterministic results with an existing JSON snapshot")
    args = parser.parse_args()

    ambient_sanity()
    prime_rows = []
    contexts = {}
    for p in TEST_PRIMES:
        row, context = finite_prime_certificate(p)
        prime_rows.append(row)
        contexts[p] = context
        print(
            f"p={p:2d} |V_p|={row['V_p']:5d} |V_p2|={row['V_p2']:5d} "
            f"fiber={row['fiber_degree']:3d} |Mon|={row['monodromy_order']:5d} "
            f"|Lin|={row['linear_image_order']:2d} |U|={row['rotation_preimage_order']:5d}"
        )

    p7 = p7_explicit_certificate(contexts[7])
    data = {
        "certificate": "HOL-01",
        "version": "1.1.1",
        "arithmetic": "exact integer/modular arithmetic; Python standard library only",
        "scope": "finite certificate at p=7; regression checks at p=3,5,7,11,13; no universal-prime claim",
        "matrices": {"M1": M1, "M2": M2, "M3": M3},
        "root": R,
        "prime_checks": prime_rows,
        "p7_explicit_loops": p7,
    }
    payload = canonical_json(data)

    if args.write_json:
        args.write_json.write_text(payload, encoding="utf-8")
        print(f"wrote {args.write_json}")
    if args.check:
        expected = args.check.read_text(encoding="utf-8")
        assert expected == payload, f"snapshot mismatch: {args.check}"
        print(f"snapshot OK: {args.check}")

    digest = hashlib.sha256(payload.encode("utf-8")).hexdigest()
    print(f"RESULTS sha256={digest}")
    print("HOL-01: ALL ASSERTIONS PASSED")


if __name__ == "__main__":
    main()
